sonar.projectKey=WeronikaPK_Lab14-Weronika_Gaj
sonar.organization=weronikapk
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**

sonar.java.binaries=backend/target/classes